### ISSUE TITLE
License main.sh (boiler plate) without attribution requirement?

### ISSUE THREAD

**Issue by zbeekman** [kvz/bash3boilerplate#14]
Hi @kvz,
First of all I want to say, your project is awesome, and you deserve credit, recognition and attribution for it! :100: However, I am wondering if adopting a [CC0](https://creativecommons.org/about/cc0/) or, IMO less desirable, the [unlicense](http://unlicense.org) might help promote adoption. Since this is intended to be a boiler plate, it is not clear to me, exactly how and under what conditions the MIT license needs to be preserved and distributed with projects that bootstrap shell scripts with bash3boilerplate. Part of this is my admitted inexperience with software licenses, but I also feel like this is a "ship of Theseus" problem at what point does borrowing components from the script require that the MIT license be included, referenced etc.

I certainly defer to your judgement here, this issue is only intended to prompt discussion and reconsideration of licensing concerns.

**Comment by kvz** [comment]
Good point!

I must admit I feel somewhat out of my comfort-zone discussing licenses. From what I know, MIT is something most developers regard as permissive and a no-strings-attached-kind-of-license. Once might argue that due to its popularity, people aren't cautious around the MIT license which might actually increase likelihood of adoption and contribution, vs a lesser known CC0 or maybe even WTFPL.

As for my intentions: I'm very cool with people not shipping the MIT License along with their bash snippets. I would like people to keep a reference to this project in their header comments though. Even if only to encourage contributions back to the source, vs that line back being lost in translation and developers only iteration on their own piece of b3bp without even knowing where it came from, how to contribute back, or where to check for updates.

Which license fits best for this you think?

**Comment by zbeekman** [comment]
> I must admit I feel somewhat out of my comfort-zone discussing licenses

Me too... they are scary and full of legalese. 

The best and most succinct source I have found yet is: http://choosealicense.com/licenses/

Looking here, the only other attractive option is probably CC0 which is a public domain dedication. No one will be required to attribute you in that circumstance, and you do risk the danger that downstream improvements are never contributed. So maybe MIT is the way to go.

Perhaps, if you stick with MIT, you should add an explicit entry in the FAQ ( #13 ) showing people how to add a comment to their code correctly adhering to the MIT license and attributing you, but licensing their derivative work under a difference license.

**Comment by kvz** [comment]
MIT with an additional permissive clause in the source header comments that the license itself need not be redistributed, but that section does, seems ok to me. It might not hold up in court, but I wasn't planning on dragging anybody in there anyway :) if people decide to not respect it, so be it. But I think most people will, which is good enough.

Would you be okay with making a proposal PR for this?

**Comment by kvz** [comment]
I am not a lawyer, but I what do you think about this PR #28 @zbeekman @rouson ?

**Comment by rouson** [comment]
@kvz 

I'm not a lawyer either.  I suggest using a standard license and changing only the contributor information.  Presumably the license was drafted by lawyers and none of us really has any clue about the legal ramifications even though admittedly they are unlikely to be significant in this case. At least according to [this site](http://www.dwheeler.com/essays/floss-license-slide.html), the MIT license is already the most permissive license other than a statement that the code is public domain so you've probably gone as far as any lawyer would recommend in terms of using liberal licensing terms.  

My guess is that the intentions of the contributors as expressed in writing is as important as the license.  In OpenCoarrays, for example, we will soon release some documentation that came from GCC but was written by only one author.  That author has agreed to our releasing the documentation under BSD instead of the GNU Free Documentation License.    Apparently the author's permission is sufficient for changing the relicensing under very different terms.   

In that regard, I'm curious where you wold prefer the bash3boilerplate license be placed in the OpenCoarrays [installation script](https://github.com/sourceryinstitute/opencoarrays/blob/master/install.sh).  One goal in writing that script was to reduce the explicit reference to bash3boilerplate down to a [one-line invocation](https://github.com/sourceryinstitute/opencoarrays/blob/master/install.sh#L90) of a script that contains lots of code from bash3boilerplate -- although there are lots of other lines that reference variables defined by the aforementioned invocation.  In such a use case, do you think it suffices to put the bash3boilerplate MIT license in the code invoked at the above line or should we have the bash3boilerplate license in the top-level install.sh, which is essentially the main program.  For now, I've included it install.sh [just below](https://github.com/sourceryinstitute/opencoarrays/blob/master/install.sh#L90) our usual BSD license, but I don't know if that's confusing or contradictory or overkill. 

Thoughts?

**Comment by kvz** [comment]
Hey @rouson I thought I replied to you on this one but perhaps I closed a tab before submitting! We now have a plain MIT license as to not scare anyone away. Even though my changes were meant to be more permissive, folks will be suspicious about changes and rightfully so. The website however now does add a permissive clause beyond MIT over at http://bash3boilerplate.sh/#license, allowing you to not ship the license as long as you keep the attribution comment in tact in the header of the source file. 

I think this will be good enough would you agree?

**Comment by mstreuhofer** [comment]
seems to me this issue can be closed now.
