### ISSUE TITLE
Feature Request: Method for usage parsing to ignore lines

### ISSUE THREAD

**Issue by gdevenyi** [kvz/bash3boilerplate#24]
I'd like to provide some info for the options after "--" in my script.

Ideally, I would do this by writing it in the usage doc, but it gets parsed.

I'd like a way for lines to be ignored by the parser.

**Comment by kvz** [comment]
Hi @gdevenyi, it is not 100% clear to me what you mean here. Could you perhaps add an example of what you where trying to do? Then we can replicate that locally and see it fail ourselves, that will help get our minds in the right place and see if we want to address it (and if we could, easily).

Disclaimer: the intention of our option parsing is to get the best option parsing that ~<100 ~readable lines of bash would allow, while introducing the least amount of external/uncommon dependencies. It is possible that we won't be able to serve all cases due to this, and that for more advances option parsing we'll need to refer to other projects.

But if anything, depending on your use case, we could add such a statement in our code, like a clause where we explicitly accept defeat and refer folks to the right place.

**Comment by gdevenyi** [comment]
Hi, sorry I see I wasn't terribly clear.

I'd like a clear way for the usage parser to "stop parsing lines", so I can include a block of text:

```
read -r -d '' usage <<-'EOF' || true # exits non-zero when EOF encountered
  -s --subject     [arg] Specific subjects to process.
  -v                     Enable verbose mode for all scripts.
  -d --debug             Enables debug mode.
  -h --help              This help page.
  -n --dry-run           Don't submit any jobs.
  -r --reg-command [arg] Provide an alternative registration command. Default="mb_register.sh"
  Commands are available after -- run, init, status, template, multiatlas, subject, resample, vote and cleanup
  Multiple commands will run multiple stages. Order is not checked.

For more details please see blah blah blah

Input file struture should be
-- input
  atlases/
  subjects/
  templates/
EOF
```
I just want to make sure that my block of text doesn't get "parsed"

**Comment by kvz** [comment]
Ah thanks for the clarification. I think the right place to add such longer descriptions would be to have a separate block of text added here https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L114. Either via a `description` variable that you set along with `usage`, or by directly inlining it in the `help` function with an `echo`. This would preserve visual vertical alignment in the help, allow us to not increase the parser's footprint, while allowing you to have any text in there.

**Comment by rouson** [comment]
I've had the same thought, but didn't think of the proposed solution.  Adding a comment above the help function to suggest this approach and explain the rationale to users would be helpful.

**Comment by kvz** [comment]
Sounds good, I'll add that

**Comment by kvz** [comment]
Please check the above commit. The end result is like this now:

![screen shot 2016-06-21 at 12 29 24](https://cloud.githubusercontent.com/assets/26752/16226490/f1936e00-37ab-11e6-9a9a-84805951f2df.png)

@gdevenyi does that seem like an okay solution for you?

**Comment by gdevenyi** [comment]
That's awesome. Makes far more sense than what I was asking :)
