### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by kvz** [kvz/bash3boilerplate#4]
It would be cool to have basic tests ran on Travis CI.
Bonus points for running against multiple bash versions and GNU/BSD tools. Unsure yet how to do that tho.

**Comment by zbeekman** [comment]
7a3a07989f0bbf90604f97367ec3cad528fd448e may have broken the Travis-CI setup... I don't have much experience with node/npm but that latest build  appears not to have actually run any tests. Maybe container based infrastructure wasn't such a brilliant idea? I'll try to look at the Travis-CI docs quickly.

**Comment by zbeekman** [comment]
@kvz I couldn't figure out  what's going on. Perhaps this is a non issue? Perhaps re-running the latest Travis-CI build for 7a3a079 will cause it to actually run the tests? Perhaps I miss-led you and we need to move back to legacy or Trusty builds? (I think Trusty builds are faster than legacy.)

**Comment by kvz** [comment]
Leave the failing build to me, it's expected to fail :)

**Comment by kvz** [comment]
Oh wait I misread, thought you were mentioning build were failing for your branch. Which is expected until I rerun fixtures for you work. Will look into the container fail

**Comment by kvz** [comment]
Hm. I don't see a fail based on the container change? https://travis-ci.org/kvz/bash3boilerplate/builds

**Comment by zbeekman** [comment]
I think it's silently failing, or not running what you want it to run. As I said, I could be misinterpreting the output, of which there is basically none of for this build: https://travis-ci.org/kvz/bash3boilerplate/builds/109619625

Maybe that's expected given what changes happened or didn't happen in https://github.com/kvz/bash3boilerplate/commit/30cfd19fd9d548d87893507e3fd3b9a8e2a916b8

But [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/109619626/log.txt) is the extent of the Travis-CI log for build#5; the only command I see being run is `nvm install`

**Comment by kvz** [comment]
I see what you mean now, thanks. I tried kicking more builds and the same thing happened. Likely a bug of sorts, but reverted the container infra for now

**Comment by zbeekman** [comment]
It would be nice to test on OS X too. After a certain amount (more than I'd like to admit) of trial and error I have gotten a .travis.yml together that [seems to be working](https://travis-ci.org/zbeekman/bash3boilerplate/builds/109783030).

*However*, I noticed that when some of the tests were failing, on OS X, due to missing `coreutils`/`gtimeout` and the test scripts were exiting with unexpected exit statuses, [the Travis-CI were still passing](https://travis-ci.org/zbeekman/bash3boilerplate/jobs/109782134).

I'll submit a PR to get testing on OS X and linux, but addressing any silent errors with your node_js magic is out of my league as a humble scientific programmer.

**Comment by kvz** [comment]
> scientific programmer

That's more than I could say for myself :wink: 

As you noticed in the PR updates, thanks a lot for your effort. It's impressive to me what you accomplished. 

Will close this issue as we have working tests on both Linux & OSX now :tada:
