### ISSUE TITLE
Add CTRL-C trapping

### ISSUE THREAD

**Issue by gdevenyi** [kvz/bash3boilerplate#47]
We can trap CTRL-C and call a function in bash:
https://rimuhosting.com/knowledgebase/linux/misc/trapping-ctrl-c-in-bash

``` sh
# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
        echo "** Trapped CTRL-C"
}
```

I don't have a use case right now, but it's definitely helpful to allow graceful cleanup of an interrupted script.

**Comment by kvz** [comment]
Nice find @gdevenyi 

> it's definitely helpful to allow graceful cleanup of an interrupted script.

Do you happen to know though if our current trap is not called when you press CTRL-C? That would make this more urgent. Otherwise we need to come up with a few use-cases where this offers added benefit over our current trap. Like: when would it be valuable to distinct between exit and exit by CTRL-C, and is this big enough a use-case to justify adding its weight to `main.sh`.

If we don't manage to come up with compelling cases like that, I'd still be open to the idea of adding this to the FAQ for instance

**Comment by gdevenyi** [comment]
The current trap of EXIT works properly when CTRL-C is pressed, it just might make sense to allow separate trapping.

Indeed I'm okay with a mention in the FAQ instead
